[package]
name = "esp-hal-ota"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "OTA library for esp-hal"

[lib]

[dependencies]
embedded-storage = "0.3.1"
log = { version = "0.4.22", optional = true }

[features]
default = ["log"]
log = ["dep:log"]

#esp32 = []
#esp32c2 = []
esp32c3 = []
#esp32c6 = []
#esp32h2 = []
esp32s2 = []
esp32s3 = []
