[alias]
esp32c3 = "run --no-default-features --features=esp32c3 --target=riscv32imc-unknown-none-elf"
esp32s3 = "run --no-default-features --features=esp32s3 --target=xtensa-esp32s3-none-elf"

[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor -T ./partitions.csv --erase-parts otadata"
rustflags = [
  "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
runner    = "espflash flash --monitor -T ./partitions.csv --erase-parts otadata"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[build]
target = "xtensa-esp32s3-none-elf" #default esp32s3

[env]
ESP_LOG="INFO"

[unstable]
build-std = ["core", "alloc"]
